# Generated by Django 5.0.4 on 2024-04-20 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("medico", "0003_datasabertas"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dadosmedico",
            old_name="cedula_identidade_media",
            new_name="cedula_identidade_medica",
        ),
    ]
